# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - 'ci-dev'
    
pool:
  name: 'default'
  demands:
    - agent.name -equals fix-parser-dev

steps:    
- script: 'npm install'
  displayName: 'Run npm install'
- script: 'npm run build'
  displayName: 'Run npm run build'
- script: 'pm2 start server.js --name react-server'
  displayName: 'Run pm2 server'
- script: 'pm2 list'
  displayName: 'Run server Monitor'
